// VELoura Catalogue Products Data - Extracted directly from official PDF catalogue
const VELOURA_PRODUCTS = [
  {
    id: 1,
    title: "AI Design Creator",
    slug: "ai-design-creator",
    price: 599,
    originalPrice: 699,
    category: "tech",
    categoryLabel: "Tech & Interactive",
    tagline: "Type your idea and get multiple AI-assisted design concepts that can be edited and approved before printing.",
    description: "Harness the power of generative AI to craft bespoke streetwear graphics. Simply describe your imagination—whether cyberpunk mythology, minimalist botanical sketches, or futuristic typography—and our AI engine renders high-definition print concepts tailored for your tee.",
    specialOffer: "Launch offer: 10% OFF",
    offerCode: "LAUNCH10",
    badge: "Bestseller ✦ AI Tech",
    image: "assets/products/img_p2_1.jpeg",
    pageImage: "assets/pages/page_2.png",
    pageNumber: 2,
    features: [
      "Multi-concept generative AI prompt engine",
      "Unlimited digital concept revisions before print",
      "Ultra HD Direct-to-Film (DTF) micro-pigment printing",
      "100% Super-Combed Bio-Washed Cotton (220 GSM)",
      "Zero cracking or fading after 50+ washes"
    ],
    interactiveType: "ai-generator",
    rating: 4.9,
    reviewsCount: 142
  },
  {
    id: 2,
    title: "QR Code T-Shirt",
    slug: "qr-code-tshirt",
    price: 699,
    originalPrice: 799,
    category: "tech",
    categoryLabel: "Tech & Interactive",
    tagline: "A QR code on the T-shirt can connect to a personal memory page, photos, message or video.",
    description: "Wear your digital world on your sleeve. Our precision-printed QR Code T-Shirt links seamlessly to your custom Instagram reel, private video album, Spotify playlist, portfolio, or anniversary surprise page. Scannable instantly on any smartphone camera.",
    specialOffer: "Offer: Free QR setup",
    offerCode: "FREEQR",
    badge: "Viral Trend 🔥",
    image: "assets/products/img_p3_1.jpeg",
    pageImage: "assets/pages/page_3.png",
    pageNumber: 3,
    features: [
      "Custom high-contrast scannable QR code generation",
      "Link to Spotify, YouTube, Google Drive, or Web Link",
      "Dynamic link updating capability anytime",
      "Durable laser-sharp print alignment",
      "Includes free QR setup & cloud redirect link"
    ],
    interactiveType: "qr-generator",
    rating: 4.8,
    reviewsCount: 98
  },
  {
    id: 3,
    title: "Interactive AR T-Shirt",
    slug: "interactive-ar-tshirt",
    price: 799,
    originalPrice: 899,
    category: "tech",
    categoryLabel: "Tech & Interactive",
    tagline: "A compatible phone can scan the artwork and open an augmented-reality visual or animation.",
    description: "Step into the metaverse with our Augmented Reality apparel. Scan your astronaut or neon graphic with your mobile browser or Instagram filter to trigger a mesmerizing 3D animated holographic visual leaping out of the chest.",
    specialOffer: "Launch offer: ₹100 OFF",
    offerCode: "AR100",
    badge: "Next-Gen Tech ⚡",
    image: "assets/products/img_p4_1.jpeg",
    pageImage: "assets/pages/page_4.png",
    pageNumber: 4,
    features: [
      "WebAR powered - No bulky app download needed",
      "3D spatial audio & holographic animation",
      "Compatible with iOS Safari and Android Chrome",
      "Premium heavyweight French terry blend available",
      "Guaranteed WOW factor at fests and night outs"
    ],
    interactiveType: "ar-simulator",
    rating: 5.0,
    reviewsCount: 84
  },
  {
    id: 4,
    title: "Group Design Builder",
    slug: "group-design-builder",
    price: 499,
    priceSuffix: "/ tee",
    originalPrice: 599,
    category: "squad",
    categoryLabel: "Squad & Group",
    tagline: "Create one common design for a group while adding each person's name or number.",
    description: "The ultimate uniform for your college squad, project team, sports league, or road trip crew. Keep a unified front aesthetic while personalizing the back with individual squad names, nicknames, and jersey numbers.",
    specialOffer: "Group offer: 5+ tees get 10% OFF",
    offerCode: "SQUAD10",
    badge: "Squad Favorite 👥",
    image: "assets/products/img_p5_1.jpeg",
    pageImage: "assets/pages/page_5.png",
    pageNumber: 5,
    features: [
      "Bulk roster entry for squad names & jersey numbers",
      "Coordinated typography and back-print layout",
      "Available across unisex sizes from S to 3XL",
      "Volume discount automatically calculated in cart",
      "Free group packaging with personalized tags"
    ],
    interactiveType: "group-builder",
    rating: 4.9,
    reviewsCount: 215
  },
  {
    id: 5,
    title: "Design Your Story Collection",
    slug: "design-your-story",
    price: 649,
    originalPrice: 749,
    category: "personal",
    categoryLabel: "Personal & Story",
    tagline: "Answer a few simple questions and turn your interests, memories and personality into a custom design.",
    description: "Every journey has an aesthetic. Take our brief 4-question lifestyle questionnaire about your passions (Nature, Travel, Music, Ambition), and our boutique design studio generates a poetic, bespoke illustration with wanderlust quotes.",
    specialOffer: "Offer: Free first design revision",
    offerCode: "STORYFREE",
    badge: "Signature Series ✨",
    image: "assets/products/img_p6_1.jpeg",
    pageImage: "assets/pages/page_6.png",
    pageNumber: 6,
    features: [
      "Interactive 4-step story questionnaire builder",
      "Custom scenic and botanical artwork generation",
      "Includes 1 free professional designer revision",
      "Delivered with a printed Story Card certificate",
      "220 GSM luxury soft combed cotton"
    ],
    interactiveType: "story-builder",
    rating: 4.9,
    reviewsCount: 67
  },
  {
    id: 6,
    title: "Eco-Friendly Print-on-Demand",
    slug: "eco-friendly-pod",
    price: 599,
    originalPrice: 699,
    category: "eco",
    categoryLabel: "Eco & Community",
    tagline: "Printed only after ordering, helping reduce unsold stock; eco-conscious packaging can be offered where available.",
    description: "Fashion with a conscious soul. By manufacturing strictly on-demand, we eliminate 100% of unsold warehouse textile waste. Crafted with water-based non-toxic inks and packed in compostable kraft paper boxes with recycled botanical tape.",
    specialOffer: "Launch offer: Free eco packaging",
    offerCode: "ECOFREE",
    badge: "100% Sustainable 🌿",
    image: "assets/products/img_p7_1.jpeg",
    pageImage: "assets/pages/page_7.png",
    pageNumber: 7,
    features: [
      "Zero-waste on-demand micro manufacturing",
      "Water-based, OEKO-TEX certified organic inks",
      "Biodegradable recycled kraft gift packaging",
      "Supports sustainable carbon-offset initiatives",
      "Ultra-breathable all-weather cotton"
    ],
    interactiveType: "standard",
    rating: 4.8,
    reviewsCount: 53
  },
  {
    id: 7,
    title: "Mood T-Shirt",
    slug: "mood-tshirt",
    price: 499,
    originalPrice: 549,
    category: "personal",
    categoryLabel: "Personal & Story",
    tagline: "Choose a mood and receive a design built around that feeling, such as happy, calm, focused or excited.",
    description: "Wear your state of mind. Pick your current frequency—Happy, Chill, Focused, or Excited—and receive an expressive badge design curated for your everyday emotional resonance. Perfect conversation starter.",
    specialOffer: "Student offer: ₹50 OFF",
    offerCode: "STUDENT50",
    badge: "Student Pick 🎓",
    image: "assets/products/img_p8_1.jpeg",
    pageImage: "assets/pages/page_8.png",
    pageNumber: 8,
    features: [
      "Interactive mood selection palette",
      "Iconic retro emoticon aesthetics & colorways",
      "Pocket print or centered chest print options",
      "Lightweight breathable combed cotton",
      "Flat ₹50 discount for all college students"
    ],
    interactiveType: "mood-selector",
    rating: 4.7,
    reviewsCount: 110
  },
  {
    id: 8,
    title: "Secret Message T-Shirt",
    slug: "secret-message-tshirt",
    price: 549,
    originalPrice: 649,
    category: "personal",
    categoryLabel: "Personal & Story",
    tagline: "A personal message is hidden creatively inside the artwork for a small surprise or private meaning.",
    description: "More than meets the eye. From afar it looks like a chic cryptic geometric pattern or standard phrase, but up close or under angled view, a hidden cipher or uplifting personal confession reveals itself.",
    specialOffer: "Offer: Free hidden-message layout",
    offerCode: "SECRETFREE",
    badge: "Hidden Cipher 🕵️",
    image: "assets/products/img_p9_1.jpeg",
    pageImage: "assets/pages/page_9.png",
    pageNumber: 9,
    features: [
      "Optical illusion typographic engineering",
      "Custom hidden text of your choice (up to 20 chars)",
      "Free creative typesetting by our graphic team",
      "Premium matte stealth black base tee",
      "Includes mini decoder card for gifting"
    ],
    interactiveType: "secret-decoder",
    rating: 4.9,
    reviewsCount: 79
  },
  {
    id: 9,
    title: "Glow / Reflective T-Shirt",
    slug: "glow-reflective-tshirt",
    price: 699,
    originalPrice: 799,
    category: "tech",
    categoryLabel: "Tech & Interactive",
    tagline: "Reflective or glow-style elements create a different look under low light or camera flash.",
    description: "Designed to dominate the night. Under natural daylight, the print shows a clean minimalist artwork. Step under club UV lights or take a photo with camera flash, and the luminescent ink flashes an electric neon glow.",
    specialOffer: "Launch offer: ₹100 OFF",
    offerCode: "GLOW100",
    badge: "Flash Reactive ⚡",
    image: "assets/products/img_p10_1.jpeg",
    pageImage: "assets/pages/page_10.png",
    pageNumber: 10,
    features: [
      "Dual-state pigment: Subtle daylight vs Bright Neon glow",
      "High-index 3M reflective vinyl & phosphorescent ink",
      "Night club, rave & night run safety certified",
      "Retains glow charge with just 5 mins sunlight exposure",
      "Deep jet black 220 GSM heavyweight cotton"
    ],
    interactiveType: "glow-toggle",
    rating: 5.0,
    reviewsCount: 129
  },
  {
    id: 10,
    title: "Mix & Match T-Shirt",
    slug: "mix-and-match-tshirt",
    price: 499,
    originalPrice: 599,
    category: "personal",
    categoryLabel: "Personal & Story",
    tagline: "Choose the base, font, graphic, sleeve and back design to build your own combination.",
    description: "You are the creative director. Choose your base tee shade, select from curated streetwear fonts, insert graphic emblems, select sleeve accents, and add back numbering to create an authentic signature piece.",
    specialOffer: "Offer: Free basic customization",
    offerCode: "MIXFREE",
    badge: "Modular Custom 🎨",
    image: "assets/products/img_p11_1.jpeg",
    pageImage: "assets/pages/page_11.png",
    pageNumber: 11,
    features: [
      "Modular design matrix with 100+ design combos",
      "Font choices: Gothic, Futura, Minimal Serif, Athletic",
      "Front chest + sleeve + full back print zones",
      "Real-time visual mockup updates",
      "No setup or cliché plate charges"
    ],
    interactiveType: "mix-match",
    rating: 4.8,
    reviewsCount: 92
  },
  {
    id: 11,
    title: "Draw It, We Print It",
    slug: "draw-it-we-print-it",
    price: 599,
    originalPrice: 699,
    category: "personal",
    categoryLabel: "Personal & Story",
    tagline: "Upload your own hand-drawn artwork and turn it into a clean printable T-shirt design.",
    description: "Turn paper notebook doodles, kids' cute art, or professional tablet sketches into wearable gallery fashion. Our studio cleans up pencil smudges, vectors the linework, balances colors, and produces crisp prints.",
    specialOffer: "Offer: Free artwork cleanup",
    offerCode: "DRAWFREE",
    badge: "Artist Canvas 🖌️",
    image: "assets/products/img_p12_1.jpeg",
    pageImage: "assets/pages/page_12.png",
    pageNumber: 12,
    features: [
      "Free background cleanup & vector conversion",
      "Accepts mobile camera photos of paper drawings",
      "Digital proof sent for approval before printing",
      "Preserves original hand-drawn textures and charm",
      "Perfect sentimental gift for loved ones"
    ],
    interactiveType: "draw-upload",
    rating: 4.9,
    reviewsCount: 76
  },
  {
    id: 12,
    title: "Voice-to-Design T-Shirt",
    slug: "voice-to-design-tshirt",
    price: 549,
    originalPrice: 649,
    category: "tech",
    categoryLabel: "Tech & Interactive",
    tagline: "Describe your idea by voice and turn it into a design direction before placing the order.",
    description: "Can't find the right words on keyboard? Just tap record and speak your heart out in Tamil, English, or Tanglish. Our voice intelligence engine transcribes the emotion, key motifs, and visual prompts directly into custom graphics.",
    specialOffer: "Student offer: 10% OFF",
    offerCode: "VOICE10",
    badge: "Speech AI 🎙️",
    image: "assets/products/img_p13_1.jpeg",
    pageImage: "assets/pages/page_13.png",
    pageNumber: 13,
    features: [
      "Voice note capture & audio waveform rendering",
      "Multilingual prompt understanding (Tanglish/English)",
      "Optional scannable voice soundwave print on back",
      "Instant translation to art generation prompts",
      "Super soft comfort-fit premium tee"
    ],
    interactiveType: "voice-recorder",
    rating: 4.8,
    reviewsCount: 61
  },
  {
    id: 13,
    title: "Puzzle T-Shirt",
    slug: "puzzle-tshirt",
    price: 649,
    priceSuffix: "/ tee",
    originalPrice: 749,
    category: "squad",
    categoryLabel: "Squad & Group",
    tagline: "Split one big picture across several T-shirts so the full design appears when the group stands together.",
    description: "Unity through design. Split a continuous breathtaking panoramic mountain range, graffiti mural, or funny squad illustration across 2, 3, or 4 t-shirts. When you stand side-by-side, the puzzle locks into one magnificent visual masterpiece.",
    specialOffer: "Group offer: ₹150 OFF on 4+ tees",
    offerCode: "PUZZLE150",
    badge: "Besties & Trio 🧩",
    image: "assets/products/img_p14_1.jpeg",
    pageImage: "assets/pages/page_14.png",
    pageNumber: 14,
    features: [
      "Seamless multi-shirt edge-to-edge alignment",
      "Options for 2-pack (Couples/Besties) or 3-4 pack (Squad)",
      "Individually labeled order packages (Piece 1, 2, 3)",
      "High precision laser calibration during printing",
      "Flat ₹150 discount when buying 4 or more pieces"
    ],
    interactiveType: "puzzle-view",
    rating: 5.0,
    reviewsCount: 134
  },
  {
    id: 14,
    title: "Limited Memory Drop",
    slug: "limited-memory-drop",
    price: 599,
    originalPrice: 699,
    category: "squad",
    categoryLabel: "Squad & Group",
    tagline: "Create a limited-edition T-shirt around a special date, trip, farewell, fest or memorable event.",
    description: "College Fest 2026, Goa Farewell Trip, Culturals, or Annual Hackathon—immortalize your golden memories with vintage concert-tour style merchandise. Custom date stamps, venue list, and personalized badge crests.",
    specialOffer: "Launch offer: Free date/event detail",
    offerCode: "MEMORYFREE",
    badge: "Limited Edition 🏆",
    image: "assets/products/img_p15_1.jpeg",
    pageImage: "assets/pages/page_15.png",
    pageNumber: 15,
    features: [
      "Concert tour / College fest merchandise template",
      "Free event title & commemorative date lettering",
      "Backside festival lineup / member roster styling",
      "Premium vintage mineral wash option available",
      "Unforgettable keepsake that lasts for years"
    ],
    interactiveType: "memory-drop",
    rating: 4.9,
    reviewsCount: 188
  },
  {
    id: 15,
    title: "T-Shirt Design Voting",
    slug: "tshirt-design-voting",
    price: 499,
    originalPrice: 599,
    category: "eco",
    categoryLabel: "Eco & Community",
    tagline: "Customers vote for upcoming designs, and the most popular concept can become the next collection.",
    description: "Democratic streetwear fashion. Browse upcoming prototype drops submitted by our design community, cast your live vote, and unlock an exclusive ₹50 discount voucher for backing the winner. The highest-voted piece goes into limited production.",
    specialOffer: "Voter offer: ₹50 OFF next order",
    offerCode: "VOTER50",
    badge: "Community Voted 🗳️",
    image: "assets/products/img_p16_1.jpeg",
    pageImage: "assets/pages/page_16.png",
    pageNumber: 16,
    features: [
      "Live community voting system with instant leaderboards",
      "Every vote earns an instant ₹50 discount coupon",
      "Pre-order winning drops before they sell out",
      "Encourages student creators and graphic artists",
      "Exclusive numbered limited-run tags"
    ],
    interactiveType: "voting-hub",
    rating: 4.9,
    reviewsCount: 340
  },
  {
    id: 16,
    title: "One Design, Many Styles",
    slug: "one-design-many-styles",
    price: 549,
    originalPrice: 649,
    category: "personal",
    categoryLabel: "Personal & Story",
    tagline: "Choose one idea and see it in different styles such as minimal, cartoon, vintage or typography.",
    description: "Love an idea but want your specific aesthetic vibe? Take a single motif (like our iconic Alpha Wolf) and instantly inspect it rendered in Minimal Linework, Vibrant Cartoon, Retro Vintage Sunset, or Intricate Geometric Typography.",
    specialOffer: "Offer: Choose up to 4 styles",
    offerCode: "STYLE4",
    badge: "4-in-1 Styles 🎭",
    image: "assets/products/img_p17_1.jpeg",
    pageImage: "assets/pages/page_17.png",
    pageNumber: 17,
    features: [
      "4 distinct aesthetic variations for every motif",
      "Minimalist Line Art, Japanese Cartoon, Retro 80s Vintage, Geometric Typographic",
      "Side-by-side style comparison selector",
      "Custom color base compatibility",
      "Premium breathable bio-washed cotton"
    ],
    interactiveType: "style-switcher",
    rating: 4.8,
    reviewsCount: 88
  }
];

// Available T-Shirt Colors for Studio Customizer
const TSHIRT_COLORS = [
  { name: "Obsidian Black", hex: "#121214", textColor: "#ffffff", mockup: "assets/mockups/tshirt_obsidian_black.png" },
  { name: "Crisp White", hex: "#f8fafc", textColor: "#111827", mockup: "assets/mockups/tshirt_crisp_white.png" },
  { name: "Vintage Charcoal", hex: "#2b2d30", textColor: "#ffffff", mockup: "assets/mockups/tshirt_vintage_charcoal.png" },
  { name: "Sage Forest", hex: "#2d3e35", textColor: "#ffffff", mockup: "assets/mockups/tshirt_sage_forest.png" },
  { name: "Midnight Navy", hex: "#1a233a", textColor: "#ffffff", mockup: "assets/mockups/tshirt_midnight_navy.png" },
  { name: "Desert Sand", hex: "#d8c4b6", textColor: "#111827", mockup: "assets/mockups/tshirt_desert_sand.png" },
  { name: "Crimson Maroon", hex: "#4a1521", textColor: "#ffffff", mockup: "assets/mockups/tshirt_crimson_maroon.png" }
];

// Available Fonts for Customizer
const STUDIO_FONTS = [
  { id: "outfit", name: "Outfit Streetwear", family: "'Outfit', sans-serif" },
  { id: "jakarta", name: "Modern Minimal", family: "'Plus Jakarta Sans', sans-serif" },
  { id: "cormorant", name: "Luxury Serif", family: "'Cormorant Garamond', Georgia, serif" },
  { id: "space", name: "Cyberpunk Tech", family: "'Space Grotesk', monospace" }
];

// Customer Testimonials
const CUSTOMER_REVIEWS = [
  {
    name: "Karthik Raja",
    college: "Anna University, Chennai",
    rating: 5,
    verified: true,
    product: "Group Design Builder",
    comment: "Enga college symposium team-ku 18 tees order pannom. Material semma thick (220 GSM), print quality clean ah irukku. ₹499-ku idhuvida best deal kedaikaadhu!",
    date: "2 days ago"
  },
  {
    name: "Priyanka S.",
    college: "Loyola College",
    rating: 5,
    verified: true,
    product: "QR Code T-Shirt",
    comment: "En friend birthday gift-ku custom Spotify song link QR vachu print pannom. Phone camera-la scan pannavodane song play aachu, friend shocked and happy! Thank you VELoura team!",
    date: "5 days ago"
  },
  {
    name: "Akash & Team",
    college: "PSG Tech, Coimbatore",
    rating: 5,
    verified: true,
    product: "Puzzle T-Shirt",
    comment: "Naanga 3 peru Goa trip-ku panoramic mountain puzzle tee potrundhom. Tourists ellam engala photo edukka start pannitaanga. Quality is peak luxury!",
    date: "1 week ago"
  },
  {
    name: "Sneha Varman",
    college: "SRM University",
    rating: 5,
    verified: true,
    product: "Interactive AR T-Shirt",
    comment: "AR astronaut phone-la scan panna visual animation live-ah varudhu! Fest la ellarum engitta 'idhu enga vangina' nu ketaanga. Highly recommended!",
    date: "2 weeks ago"
  },
  {
    name: "Dinesh Kumar",
    college: "VIT Vellore",
    rating: 5,
    verified: true,
    product: "AI Design Creator",
    comment: "Prompt kuduthu 5 seconds-la custom graphic generate aagi print panna mudinjadhu. Heavyweight 220 GSM fabric feels like international luxury streetwear!",
    date: "3 weeks ago"
  },
  {
    name: "Rithika M.",
    college: "SSN College of Engineering",
    rating: 5,
    verified: true,
    product: "Secret Glow-in-the-Dark",
    comment: "Night culturals apo uv light-la glow aachu, stage-la semma visual effect! Bio-washed cotton romba soft ah irukku even after multiple machine washes.",
    date: "1 month ago"
  }
];
